import os
import re
import threading
import subprocess
from pathlib import Path
from dotenv import load_dotenv
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

load_dotenv()

WORKSPACE = Path(os.environ["WORKSPACE_DIR"])
GITHUB_OWNER = os.environ["GITHUB_OWNER"]

app = App(token=os.environ["SLACK_BOT_TOKEN"])

TRIGGER_PATTERN = re.compile(
    r"(作りたい|したい|欲しい|○○な|アプリ|ツール|bot|Bot|システム|サービス|機能|自動化)",
    re.IGNORECASE,
)

# thread_ts -> {task: str, channel: str}
pending: dict[str, dict] = {}

# thread_ts -> {original: str, history: list[str], channel: str}
waiting: dict[str, dict] = {}


# ---------------------------------------------------------------------------
# claude CLI helper
# ---------------------------------------------------------------------------

def run_claude(prompt: str, cwd: str | None = None, timeout: int = 300) -> tuple[int, str]:
    """Run claude -p <prompt> and return (returncode, stdout)."""
    result = subprocess.run(
        ["claude", "-p", prompt, "--dangerously-skip-permissions"],
        cwd=cwd or str(WORKSPACE),
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    output = result.stdout.strip()
    if not output and result.stderr.strip():
        print(f"[claude stderr] {result.stderr.strip()[:500]}", flush=True)
        output = result.stderr.strip()
    return result.returncode, output


# ---------------------------------------------------------------------------
# Idea evaluation via /shape-request skill
# ---------------------------------------------------------------------------

def evaluate_idea(text: str) -> tuple[str, str, str]:
    """Returns (judgment, full_response, task_description).

    Calls the workspace /shape-request skill so the evaluation logic
    stays in sync with .claude/skills/shape-request.
    """
    _, output = run_claude(f"/shape-request {text}")

    if "**GO**" in output:
        judgment = "GO"
    elif "**WAIT**" in output:
        judgment = "WAIT"
    else:
        judgment = "REJECT"

    task_match = re.search(r"## 次アクション\n(.+?)(?:\n##|$)", output, re.DOTALL)
    task_description = task_match.group(1).strip() if task_match else text

    return judgment, output, task_description


def reevaluate_idea(original: str, history: list[str]) -> tuple[str, str, str]:
    """Re-evaluate with conversation history appended to the original request."""
    conversation = original + "\n\n--- 追加情報 ---\n" + "\n".join(history)
    return evaluate_idea(conversation)


# ---------------------------------------------------------------------------
# Pipeline: repo setup → implementation → PR
# ---------------------------------------------------------------------------

def _run(cmd: list[str], cwd: str | None = None) -> tuple[int, str, str]:
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return r.returncode, r.stdout, r.stderr


def setup_repo(repo_name: str, task_description: str) -> Path:
    project_dir = WORKSPACE / repo_name
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "README.md").write_text(f"# {repo_name}\n\n{task_description}\n")
    (project_dir / ".gitignore").write_text("__pycache__/\n*.py[cod]\n.env\n.venv/\n")
    (project_dir / "TASK.md").write_text(
        "# TASK\n\n## Backlog\n\n- [ ] Initial implementation\n"
    )

    cwd = str(project_dir)
    _run(["git", "init"], cwd)
    _run(["git", "checkout", "-b", "main"], cwd)
    _run(["git", "config", "user.email", "slack-shape-bot@local"], cwd)
    _run(["git", "config", "user.name", "slack-shape-bot"], cwd)
    _run(["git", "add", "."], cwd)
    _run(["git", "commit", "-m", "Initial scaffold"], cwd)

    _run(
        ["gh", "repo", "create", f"{GITHUB_OWNER}/{repo_name}",
         "--private", "--source=.", "--remote=origin", "--push"],
        cwd,
    )

    _run(["git", "checkout", "-b", "feature/initial-implementation"], cwd)
    return project_dir


def run_implementation(project_dir: Path, task_description: str) -> bool:
    code, _ = run_claude(
        f"/direct-task {task_description}",
        cwd=str(project_dir),
        timeout=600,
    )
    return code == 0


def create_pr(project_dir: Path, repo_name: str, task_description: str) -> str:
    cwd = str(project_dir)
    _run(["git", "add", "."], cwd)
    rc, _, _ = _run(["git", "diff", "--cached", "--quiet"], cwd)
    if rc != 0:
        _run(["git", "commit", "-m", "Implement initial version"], cwd)

    _run(["git", "push", "-u", "origin", "feature/initial-implementation"], cwd)

    _, stdout, _ = _run(
        [
            "gh", "pr", "create",
            "--title", f"Implement {repo_name}",
            "--body",
            f"## Summary\n\n{task_description}\n\n"
            "🤖 Generated by slack-shape-bot",
            "--base", "main",
        ],
        cwd,
    )
    return stdout.strip().split("\n")[-1]


def run_pipeline(repo_name: str, task_description: str, channel: str, thread_ts: str):
    def post(msg: str):
        app.client.chat_postMessage(channel=channel, thread_ts=thread_ts, text=msg)

    try:
        post(f":hammer_and_wrench: リポジトリ `{repo_name}` を作成中...")
        project_dir = setup_repo(repo_name, task_description)
        post(":robot_face: 実装中... しばらくお待ちください")
        run_implementation(project_dir, task_description)
        post(":twisted_rightwards_arrows: PR を作成中...")
        pr_url = create_pr(project_dir, repo_name, task_description)
        post(f":white_check_mark: 完了！\nPR: {pr_url}")
    except Exception as e:
        post(f":x: エラーが発生しました:\n```{e}```")


# ---------------------------------------------------------------------------
# Slack event handler
# ---------------------------------------------------------------------------

@app.event("message")
def handle_message(event, say, client):
    if event.get("bot_id") or event.get("subtype"):
        return

    text = event.get("text", "")
    thread_ts = event.get("thread_ts")

    # Reply in a thread waiting for a project name (GO confirmed)
    if thread_ts and thread_ts in pending:
        raw = text.strip().lower()
        repo_name = re.sub(r"[^a-z0-9-]", "-", raw).strip("-")
        repo_name = re.sub(r"-{2,}", "-", repo_name)  # collapse consecutive hyphens
        if not repo_name or len(repo_name) > 100:
            say(
                "リポジトリ名が不正です。英数字とハイフンのみ・100文字以内で入力してください。\n"
                "例: `my-app`",
                thread_ts=thread_ts,
            )
            return

        info = pending.pop(thread_ts)
        say(f"`{repo_name}` で作業を開始します！", thread_ts=thread_ts)
        threading.Thread(
            target=run_pipeline,
            args=(repo_name, info["task"], event["channel"], thread_ts),
            daemon=True,
        ).start()
        return

    # Reply in a thread waiting for clarification (WAIT)
    if thread_ts and thread_ts in waiting:
        info = waiting[thread_ts]
        info["history"].append(text)

        ts = event["ts"]
        try:
            client.reactions_add(channel=event["channel"], name="thinking_face", timestamp=ts)
        except Exception:
            pass

        judgment, result_text, task_description = reevaluate_idea(
            info["original"], info["history"]
        )
        say(text=result_text, thread_ts=thread_ts)

        try:
            client.reactions_remove(channel=event["channel"], name="thinking_face", timestamp=ts)
        except Exception:
            pass

        if judgment == "GO":
            waiting.pop(thread_ts)
            pending[thread_ts] = {"task": task_description, "channel": event["channel"]}
            say(
                "GO です！プロジェクト名を教えてください（例: `my-app`）\n"
                "※ 英数字・ハイフンのみ",
                thread_ts=thread_ts,
            )
        elif judgment == "REJECT":
            waiting.pop(thread_ts)
        # WAIT: keep waiting, history already updated
        return

    # New idea message
    if not TRIGGER_PATTERN.search(text):
        return

    ts = event["ts"]
    try:
        client.reactions_add(channel=event["channel"], name="thinking_face", timestamp=ts)
    except Exception:
        pass

    judgment, result_text, task_description = evaluate_idea(text)
    say(text=result_text, thread_ts=ts)

    try:
        client.reactions_remove(channel=event["channel"], name="thinking_face", timestamp=ts)
    except Exception:
        pass

    if judgment == "GO":
        pending[ts] = {"task": task_description, "channel": event["channel"]}
        say(
            "GO です！プロジェクト名を教えてください（例: `my-app`）\n"
            "※ 英数字・ハイフンのみ",
            thread_ts=ts,
        )
    elif judgment == "WAIT":
        waiting[ts] = {
            "original": text,
            "history": [],
            "channel": event["channel"],
        }


if __name__ == "__main__":
    handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    handler.start()
